[package]
name = "nanojpeg-rs"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0"

[dev-dependencies]

[features]
default = ["libc"]
libc = []
